package plugin

import (
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// KnownPlugins maps short names to their full Go import paths.
var KnownPlugins = map[string]string{
	"n8n": "github.com/stoa-hq/stoa-plugins/n8n",
}

// ResolvePackage resolves a short plugin name or full Go import path.
// Unknown names are returned as-is (treated as a full import path).
func ResolvePackage(nameOrPath string) string {
	if pkg, ok := KnownPlugins[nameOrPath]; ok {
		return pkg
	}
	return nameOrPath
}

// FindModuleRoot walks up from dir until it finds a go.mod file.
// Returns an error when no go.mod is found (i.e. not a Go module root).
func FindModuleRoot(dir string) (string, error) {
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found; run this command from the Stoa source directory")
		}
		dir = parent
	}
}

// Installer manages plugin installation within a Go module source tree.
type Installer struct {
	moduleRoot string
	binaryPath string
}

// NewInstaller creates an Installer for the given module root.
// binaryPath is the path of the running binary to be replaced after rebuild.
func NewInstaller(moduleRoot, binaryPath string) *Installer {
	return &Installer{moduleRoot: moduleRoot, binaryPath: binaryPath}
}

// Install fetches the plugin package, adds it to the generated imports file,
// and rebuilds the binary in-place.
func (i *Installer) Install(pkg string) error {
	imports, err := i.readImports()
	if err != nil {
		return err
	}
	for _, imp := range imports {
		if imp == pkg {
			return fmt.Errorf("plugin %q is already installed", pkg)
		}
	}

	fmt.Printf("Fetching %s...\n", pkg)
	if err := i.run("go", "get", pkg+"@latest"); err != nil {
		return fmt.Errorf("go get: %w", err)
	}

	if err := i.writePluginsFile(append(imports, pkg)); err != nil {
		return fmt.Errorf("updating plugins file: %w", err)
	}

	return i.rebuild()
}

// Remove removes the plugin import, runs go mod tidy, and rebuilds.
func (i *Installer) Remove(pkg string) error {
	imports, err := i.readImports()
	if err != nil {
		return err
	}

	filtered := make([]string, 0, len(imports))
	found := false
	for _, imp := range imports {
		if imp == pkg {
			found = true
			continue
		}
		filtered = append(filtered, imp)
	}
	if !found {
		return fmt.Errorf("plugin %q is not installed", pkg)
	}

	if err := i.writePluginsFile(filtered); err != nil {
		return fmt.Errorf("updating plugins file: %w", err)
	}

	fmt.Println("Running go mod tidy...")
	if err := i.run("go", "mod", "tidy"); err != nil {
		return fmt.Errorf("go mod tidy: %w", err)
	}

	return i.rebuild()
}

// ListInstalled returns the import paths of all installed plugins.
func (i *Installer) ListInstalled() ([]string, error) {
	return i.readImports()
}

// pluginsFile returns the path to cmd/stoa/plugins_generated.go.
func (i *Installer) pluginsFile() string {
	return filepath.Join(i.moduleRoot, "cmd", "stoa", "plugins_generated.go")
}

func (i *Installer) readImports() ([]string, error) {
	data, err := os.ReadFile(i.pluginsFile())
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading plugins file: %w", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", data, parser.ImportsOnly)
	if err != nil {
		return nil, fmt.Errorf("parsing plugins file: %w", err)
	}

	var imports []string
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		imports = append(imports, path)
	}
	return imports, nil
}

func (i *Installer) writePluginsFile(imports []string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by \"stoa plugin install\". DO NOT EDIT.\n")
	sb.WriteString("package main\n")
	if len(imports) > 0 {
		sb.WriteString("\nimport (\n")
		for _, imp := range imports {
			fmt.Fprintf(&sb, "\t_ %q\n", imp)
		}
		sb.WriteString(")\n")
	}

	src, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("formatting plugins file: %w", err)
	}
	return os.WriteFile(i.pluginsFile(), src, 0644)
}

func (i *Installer) rebuild() error {
	fmt.Printf("Building stoa → %s\n", i.binaryPath)
	if err := i.run("go", "build", "-o", i.binaryPath, "./cmd/stoa"); err != nil {
		return fmt.Errorf("build failed: %w", err)
	}
	fmt.Println("Done. Restart stoa to apply changes.")
	return nil
}

func (i *Installer) run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = i.moduleRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
