// Code generated by "stoa plugin install". DO NOT EDIT.
package main

import (
	_ "github.com/stoa-hq/stoa-plugins/meilisearch"
	_ "github.com/stoa-hq/stoa-plugins/n8n"
	_ "github.com/stoa-hq/stoa-plugins/stripe"
)
