#!/bin/sh
set -e

# Mapping: short name → full import path.
# Keep in sync with internal/plugin/installer.go KnownPlugins.
resolve_plugin() {
  case "$1" in
    n8n)    echo "github.com/stoa-hq/stoa-plugins/n8n" ;;
    stripe) echo "github.com/stoa-hq/stoa-plugins/stripe" ;;
    *)      echo "$1" ;;
  esac
}

# Check if a value looks like a local path.
is_local_path() {
  case "$1" in
    ./*|../*|/*) return 0 ;;
    *)           return 1 ;;
  esac
}

# Read the module name from a go.mod file.
read_module_name() {
  sed -n 's/^module[[:space:]]*//p' "$1/go.mod" | head -1
}

PLUGINS_CSV="${1:-}"
if [ -z "$PLUGINS_CSV" ]; then
  echo "No plugins requested, skipping."
  exit 0
fi

STOA_MODULE=$(read_module_name ".")

IMPORT_PATHS=""
IFS=','
for name in $PLUGINS_CSV; do
  name=$(echo "$name" | tr -d ' ')
  [ -z "$name" ] && continue

  if is_local_path "$name"; then
    # Local plugin inside the build context.
    if [ ! -d "$name" ]; then
      echo "ERROR: local plugin directory not found: $name" >&2
      exit 1
    fi

    if [ -f "$name/go.mod" ]; then
      # External module — needs replace directive.
      plugin_module=$(read_module_name "$name")
      echo "Installing local plugin: $name (module: $plugin_module)"
      go mod edit -replace "${plugin_module}=${name}"
      import_path="$plugin_module"
    else
      # Internal — part of the Stoa module, derive import path.
      rel_path=$(echo "$name" | sed 's|^\./||')
      import_path="${STOA_MODULE}/${rel_path}"
      echo "Installing local plugin: $name → $import_path"
    fi

    IMPORT_PATHS="${IMPORT_PATHS} ${import_path}"
  else
    resolved=$(resolve_plugin "$name")
    echo "Installing plugin: $name → $resolved"
    go get "${resolved}@latest"
    IMPORT_PATHS="${IMPORT_PATHS} ${resolved}"
  fi
done
unset IFS

for target_dir in cmd/stoa cmd/stoa-store-mcp; do
  outfile="${target_dir}/plugins_generated.go"
  mkdir -p "$target_dir"
  {
    echo '// Code generated by docker-plugins.sh. DO NOT EDIT.'
    echo 'package main'
    echo ''
    echo 'import ('
    for p in $IMPORT_PATHS; do
      echo "	_ \"${p}\""
    done
    echo ')'
  } > "$outfile"
  echo "Generated $outfile"
done

go mod tidy
echo "Plugin installation complete."
